# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 582)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 561, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 431, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(70, 50, 51, 31))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.x1LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.x1LineEdit.setGeometry(QtCore.QRect(40, 50, 31, 31))
        self.x1LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.x1LineEdit.setObjectName("x1LineEdit")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(150, 50, 51, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.x2LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.x2LineEdit.setGeometry(QtCore.QRect(120, 50, 31, 31))
        self.x2LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.x2LineEdit.setObjectName("x2LineEdit")
        self.x3LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.x3LineEdit.setGeometry(QtCore.QRect(200, 50, 31, 31))
        self.x3LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.x3LineEdit.setObjectName("x3LineEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(230, 50, 51, 31))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.x4LineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.x4LineEdit.setGeometry(QtCore.QRect(280, 50, 31, 31))
        self.x4LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.x4LineEdit.setObjectName("x4LineEdit")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(310, 50, 101, 31))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 260, 431, 181))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(70, 50, 51, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.xLineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_11.setGeometry(QtCore.QRect(40, 50, 31, 31))
        self.xLineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_11.setObjectName("xLineEdit_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(150, 50, 51, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.xLineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_12.setGeometry(QtCore.QRect(120, 50, 31, 31))
        self.xLineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_12.setObjectName("xLineEdit_12")
        self.xLineEdit_13 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_13.setGeometry(QtCore.QRect(200, 50, 31, 31))
        self.xLineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_13.setObjectName("xLineEdit_13")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(230, 50, 51, 31))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.xLineEdit_14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_14.setGeometry(QtCore.QRect(280, 50, 31, 31))
        self.xLineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_14.setObjectName("xLineEdit_14")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(310, 50, 51, 31))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.result1LineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.result1LineEdit.setGeometry(QtCore.QRect(360, 50, 31, 31))
        self.result1LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.result1LineEdit.setObjectName("result1LineEdit")
        self.result2LineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.result2LineEdit.setGeometry(QtCore.QRect(360, 120, 31, 31))
        self.result2LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.result2LineEdit.setObjectName("result2LineEdit")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(150, 120, 51, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.xLineEdit_24 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_24.setGeometry(QtCore.QRect(280, 120, 31, 31))
        self.xLineEdit_24.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_24.setObjectName("xLineEdit_24")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(230, 120, 51, 31))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.xLineEdit_21 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_21.setGeometry(QtCore.QRect(40, 120, 31, 31))
        self.xLineEdit_21.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_21.setObjectName("xLineEdit_21")
        self.xLineEdit_22 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_22.setGeometry(QtCore.QRect(120, 120, 31, 31))
        self.xLineEdit_22.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_22.setObjectName("xLineEdit_22")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(70, 120, 51, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.xLineEdit_23 = QtWidgets.QLineEdit(self.groupBox_2)
        self.xLineEdit_23.setGeometry(QtCore.QRect(200, 120, 31, 31))
        self.xLineEdit_23.setAlignment(QtCore.Qt.AlignCenter)
        self.xLineEdit_23.setObjectName("xLineEdit_23")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(310, 120, 51, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 130, 311, 311))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(40, 40, 231, 261))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.xLabel_1 = QtWidgets.QLabel(self.widget)
        self.xLabel_1.setObjectName("xLabel_1")
        self.gridLayout.addWidget(self.xLabel_1, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.xLabel_2 = QtWidgets.QLabel(self.widget)
        self.xLabel_2.setObjectName("xLabel_2")
        self.gridLayout.addWidget(self.xLabel_2, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 1)
        self.xLabel_3 = QtWidgets.QLabel(self.widget)
        self.xLabel_3.setObjectName("xLabel_3")
        self.gridLayout.addWidget(self.xLabel_3, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 0, 1, 1)
        self.xLabel_4 = QtWidgets.QLabel(self.widget)
        self.xLabel_4.setObjectName("xLabel_4")
        self.gridLayout.addWidget(self.xLabel_4, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 0, 1, 1)
        self.zLabel = QtWidgets.QLabel(self.widget)
        self.zLabel.setObjectName("zLabel")
        self.gridLayout.addWidget(self.zLabel, 4, 1, 1, 1)
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setGeometry(QtCore.QRect(530, 460, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.calcButton.setFont(font)
        self.calcButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calcButton.setObjectName("calcButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 450, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(30, 30, 31, 31))
        self.label_19.setObjectName("label_19")
        self.bLineEdit_1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.bLineEdit_1.setGeometry(QtCore.QRect(70, 30, 31, 31))
        self.bLineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.bLineEdit_1.setObjectName("bLineEdit_1")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(100, 30, 21, 31))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.bLineEdit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.bLineEdit_2.setGeometry(QtCore.QRect(120, 30, 31, 31))
        self.bLineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.bLineEdit_2.setObjectName("bLineEdit_2")
        self.bLineEdit_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.bLineEdit_3.setGeometry(QtCore.QRect(170, 30, 31, 31))
        self.bLineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.bLineEdit_3.setObjectName("bLineEdit_3")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(150, 30, 21, 31))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.bLineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.bLineEdit_4.setGeometry(QtCore.QRect(220, 30, 31, 31))
        self.bLineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.bLineEdit_4.setObjectName("bLineEdit_4")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(200, 30, 21, 31))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(260, 30, 21, 31))
        self.label_23.setObjectName("label_23")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Симплекс-метод решения задач линейного программирования"))
        self.groupBox.setTitle(_translate("MainWindow", "Целевая функция"))
        self.label_2.setText(_translate("MainWindow", "x1+"))
        self.x1LineEdit.setText(_translate("MainWindow", "2"))
        self.label_3.setText(_translate("MainWindow", "x2+"))
        self.x2LineEdit.setText(_translate("MainWindow", "1"))
        self.x3LineEdit.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "x3+"))
        self.x4LineEdit.setText(_translate("MainWindow", "1"))
        self.label_5.setText(_translate("MainWindow", "x4-> max"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Граничные условия"))
        self.label_6.setText(_translate("MainWindow", "x1+"))
        self.xLineEdit_11.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "x2+"))
        self.xLineEdit_12.setText(_translate("MainWindow", "2"))
        self.xLineEdit_13.setText(_translate("MainWindow", "2"))
        self.label_8.setText(_translate("MainWindow", "x3+"))
        self.xLineEdit_14.setText(_translate("MainWindow", "1"))
        self.label_9.setText(_translate("MainWindow", "x4="))
        self.result1LineEdit.setText(_translate("MainWindow", "2"))
        self.result2LineEdit.setText(_translate("MainWindow", "1"))
        self.label_10.setText(_translate("MainWindow", "x2+"))
        self.xLineEdit_24.setText(_translate("MainWindow", "1"))
        self.label_11.setText(_translate("MainWindow", "x3+"))
        self.xLineEdit_21.setText(_translate("MainWindow", "1"))
        self.xLineEdit_22.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "x1+"))
        self.xLineEdit_23.setText(_translate("MainWindow", "-1"))
        self.label_13.setText(_translate("MainWindow", "x4="))
        self.groupBox_3.setTitle(_translate("MainWindow", "Результат"))
        self.label_14.setText(_translate("MainWindow", "x1="))
        self.xLabel_1.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "x2="))
        self.xLabel_2.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "x3="))
        self.xLabel_3.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "x4="))
        self.xLabel_4.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "z="))
        self.zLabel.setText(_translate("MainWindow", "0"))
        self.calcButton.setText(_translate("MainWindow", "Вычислить"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Базисный план"))
        self.label_19.setText(_translate("MainWindow", "x=("))
        self.bLineEdit_1.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", ","))
        self.bLineEdit_2.setText(_translate("MainWindow", "1"))
        self.bLineEdit_3.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", ","))
        self.bLineEdit_4.setText(_translate("MainWindow", "1"))
        self.label_22.setText(_translate("MainWindow", ","))
        self.label_23.setText(_translate("MainWindow", ")"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
